# Generated by Django 4.2.1 on 2023-06-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_expenses_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="categories",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Salary", "Salary"),
                    ("Freelance", "Freelance"),
                    ("Investment", "Investment"),
                    ("Rental Income", "Rental Income"),
                    ("Gifts", "Gifts"),
                    ("Other Income", "Other Income"),
                    ("Transportation", "Transportation"),
                    ("Housing and Groceries", "Housing and Groceries"),
                    ("Health", "Health"),
                    ("Entertainment", "Entertainment"),
                    ("Personal Care", "Personal Care"),
                    ("Other Expense", "Other Expense"),
                ],
                default="",
                max_length=255,
            ),
        ),
    ]
